---
- name: Setup docker .env file
  template:
    src: templates/dockerEnv.env
    dest: "../.env"

- name: Install prerequisites
  apt:
    name:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    state: latest
    update_cache: yes

- name: Add Docker's GPG key for Ubuntu
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Configure Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker

- name: Updated apt packages
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install the needed docker packages
  apt:
    name:
    - docker
    #- docker-ce
    #- docker-ce-cli
    #- containerd.io
    - docker-compose
    state: latest
    cache_valid_time: 3600

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user {{adminuser}} to docker group
  user:
    name: "{{adminuser}}"
    groups: docker
    append: yes

- name: Create folder for docker data
  file:
    path: "{{docker.data_dir}}"
    state: directory

- name: Create folder for traefik data
  file:
    path: "{{docker.data_dir}}/traefik/acme"
    state: directory

- name: Create acme config file for traefik
  file:
    path: "{{docker.data_dir}}/traefik/acme/acme.json"
    state: touch
    mode: '0600'

- name: Copy treafik config file
  template:
    src: templates/traefik.toml
    dest: "{{docker.data_dir}}/traefik/traefik.toml"

#- name: Create the external docker network {{docker.external_network}}
#  docker_network:
#    name: "{{docker.external_network}}"
