default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.1

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://172.17.0.1:3218/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://172.17.0.1:1880/
    require_admin: true

mqtt:
  broker: 172.17.0.1

recorder:
  db_url: mysql://homeassistant:homeassistantrocks@172.17.0.1/ha_db?charset=utf8
  purge_keep_days: 30
